# Generated by Django 5.0.2 on 2024-02-14 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_saloon', '0004_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='shout_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
