# Generated by Django 5.0.2 on 2024-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_saloon', '0009_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
