# Generated by Django 5.0.2 on 2024-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_saloon', '0010_alter_imagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_main_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
