# Generated by Django 5.0.2 on 2024-02-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_saloon', '0011_hotel_delete_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_main_img',
            new_name='Upload_image_here',
        ),
    ]
